# Generated by Django 5.1.4 on 2024-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hackthon_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
